version: "3.9"

services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - lenslocked_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "3333:8080"

volumes:
  lenslocked_data:
